version: '3'
services:
  bot:
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.bot.loadbalancer.server.port=5000
      - traefik.http.routers.bot.entrypoints=web
      - traefik.http.routers.bot.rule=Host(`${HOSTNAME}`)
      - traefik.http.middlewares.bot-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.bot.middlewares=bot-https-redirect
      - traefik.http.routers.bot-secure.entrypoints=websecure
      - traefik.http.routers.bot-secure.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.bot-secure.tls=true
      - traefik.http.routers.bot-secure.tls.certresolver=letsencrypt

networks:
  proxy:
    external: true